apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-webserver
spec:
  type: ClusterIP
  ports:
    - name: web
      port: 8080
      targetPort: 8080
  selector:
    app: {{ .Release.Name }}-webserver
