apiVersion: v1
kind: Service
metadata:
  name: airflow-webserver
  namespace: airflow
spec:
  type: NodePort
  selector:
    app: airflow-webserver
  ports:
    - name: web
      port: 80
      targetPort: 8080
      nodePort: 30080
